apiVersion: apps/v1
kind: Deployment
metadata: 
  annotations:
    app.quarkus.io/build-timestamp: 2023-06-30 - 12:45:38 +0000
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: quarkus-monitor
    app: monitor
  name: quarkus-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
      app.kubernetes.io/name: quarkus-monitor
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2023-06-30 - 12:45:38 +0000
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/name: quarkus-monitor
        app: monitor
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: quay.io/lordofthejars/quarkus-monitor:1.0.0
          imagePullPolicy: Always
          name: quarkus-monitor
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP